### ISSUE TITLE
Update GitHub language breakdown

### ISSUE THREAD

**Issue by DecimalTurn** [pdftables/vba-pdftables-api#1]
Currently, the language breakdown of the repo indicates 100% `Visual Basic .Net`. That's because the last change made to the repo was done before VBA was added to the Linguist project on GitHub ([here](https://github.com/github/linguist/commit/7fa8ca2836c069e03a4956e72fccf2a7d1d67fdf)).

![image](https://user-images.githubusercontent.com/31558169/207777800-0262c806-36c1-4b64-8a9a-54ac31efe63b.png)

Normally, any changes (even a space added to the README) would be enough to trigger a new analysis by Linguist of the languages in the repo. Hence, it would be nice to push a fictitious change so this project can appear correctly labelled as a VBA project when people search on GitHub. 

I can always create a PR for this, but I don't think this is worth adding me as a contributor 😅

**Comment by StevenMaude** [comment]
@DecimalTurn: Thanks for reporting! :heart:

I slightly edited the README and this has fixed things here:

![A screenshot showing details of the vba-pdftables-api project on GitHub. It demonstrates that the detected language for the project is now correctly Visual Basic for Applications.](https://user-images.githubusercontent.com/3818079/207836332-25cdc504-2774-49e8-b122-3d4ef1af143a.png)
